### ISSUE TITLE
stock.price error

### ISSUE THREAD

**Issue by mannyhsu** [toomore/grs#32]
ticker = '2317'
month =12
stock = Stock(ticker, month)
print stock.price
會出現 error message
==================
Traceback (most recent call last):
  File "<pyshell#21>", line 1, in <module>
    print stock.price
  File "C:\Python27\lib\site-packages\grs\fetch_data.py", line 391, in price
    return self.__serial_price()
  File "C:\Python27\lib\site-packages\grs\fetch_data.py", line 291, in __serial_price
    return list(result)
  File "C:\Python27\lib\site-packages\grs\fetch_data.py", line 290, in <genexpr>
    result = (float(i[rows]) for i in self.__raw_data)
ValueError: could not convert string to float: --

**Comment by toomore** [comment]
@mannyhsu 這個問題修復了，請使用 v0.7.0 版本，感謝！
