### ISSUE TITLE
Not able to install:  SyntaxError with invalid syntax

### ISSUE THREAD

**Issue by NasuYue** [toomore/grs#42]
```
Collecting grs
  Using cached grs-0.7.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/y8/04ps3r3d52q3mz7wfy_mgc8m0000gn/T/pip-build-og6hoafl/grs/setup.py", line 4, in <module>
        import grs
      File "/private/var/folders/y8/04ps3r3d52q3mz7wfy_mgc8m0000gn/T/pip-build-og6hoafl/grs/grs/__init__.py", line 33, in <module>
        from .fetch_data import Stock
      File "/private/var/folders/y8/04ps3r3d52q3mz7wfy_mgc8m0000gn/T/pip-build-og6hoafl/grs/grs/fetch_data.py", line 497
        raise ConnectionError(), u'IN OFFLINE, NO DATA FETCH.'
                               ^
    SyntaxError: invalid syntax
```
I am running it on macOS Sierra & Python 2.7 virtual environment.
Even I got your repository in local environment and run setup.py, it still failed anyway. 
Please help out how to install this package successfully.
Thanks for all help.

**Comment by Denielll** [comment]
I had the same problem

**Comment by tobeywang** [comment]
I had the same problem
(Python 3.5 version)

**Comment by ghost** [comment]
Same thing happen here.

**Comment by dafeng0908** [comment]
I had the same problem
(Python 3.8 version)
